apiVersion: apps/v1
kind: Deployment
metadata:
  name: about
spec:
  replicas: 5
  selector:
    matchLabels:
      app: about
  template:
    metadata:
      labels:
        app: about
    spec:
      containers:
      - image: httpd:latest
        imagePullPolicy: IfNotPresent
        name: about
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: about
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    app: about
