apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontpage
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: frontpage
  template:
    metadata:
      labels:
        app: frontpage
    spec:
      containers:
      - image: modem7/docker-starwars
        name: frontpage
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontpage
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: frontpage